
const P=['up','towards','around','through','from ... to','into','out of','past','down'];
const quiz=[
['↑','The climber moves ___ the wall.','up',['up','past','into']],
['↗','The student walks ___ the library.','towards',['towards','around','down']],
['⟳','The cyclist rides ___ the fountain.','around',['through','around','out of']],
['⇢','The train goes ___ the tunnel.','through',['through','into','past']],
['A → B','We travel ___ Lima ___ Piura.','from ... to',['from ... to','up','around']],
['↘','The ball rolls ___ the box.','into',['into','towards','past']],
['↗','The cat jumps ___ the box.','out of',['out of','down','through']],
['→ ◼','She walks ___ the bank every morning.','past',['past','into','up']],
['↓','He runs ___ the stairs.','down',['down','towards','around']]
];
const fill=[['The bird flies ___ the tree.','around'],['The girl walks ___ the school gate.','towards'],['The dog runs ___ the park entrance.','through'],['The ball goes ___ the box.','into'],['The boy comes ___ the classroom.','out of'],['We walk ___ the bank on our way home.','past']];
const pairs=[['up','move to a higher position'],['towards','move in the direction of something'],['around','move in a circle or along the sides'],['through','enter one side and leave the other'],['into','move from outside to inside'],['out of','move from inside to outside'],['past','go beyond something'],['down','move to a lower position']];
const scrambles=[['The boy walks towards the bus stop.',['The','boy','walks','towards','the','bus','stop.']],['The car goes through the tunnel.',['The','car','goes','through','the','tunnel.']],['The cat jumps out of the box.',['The','cat','jumps','out','of','the','box.']]];
let score=0,done=0;
const app=document.querySelector('#app');
app.innerHTML=`<div class="wrap"><section class="hero"><div><div class="kicker">A2 English • Interactive Practice</div><h1>Movement Mission</h1><p class="sub">Practice <b>up, towards, around, through, from…to, into, out of, past</b> and <b>down</b>.</p></div><div class="score"><div class="stat"><span>Score</span><strong id="score">0</strong></div><div class="stat"><span>Completed</span><strong id="done">0/4</strong></div></div></section><nav class="tabs"><button class="tab active" data-tab="quiz">1. Visual Quiz</button><button class="tab" data-tab="fill">2. Complete</button><button class="tab" data-tab="match">3. Match</button><button class="tab" data-tab="build">4. Builder</button></nav><section id="quiz" class="panel act"></section><section id="fill" class="panel act hidden"></section><section id="match" class="panel act hidden"></section><section id="build" class="panel act hidden"></section><p class="footer">JavaScript app • Ready for GitHub Pages • No build step</p></div>`;
const stats=()=>{document.querySelector('#score').textContent=score;document.querySelector('#done').textContent=`${done}/4`};
const finish=(pts,btn)=>{if(btn.disabled)return;score+=pts;done=Math.min(4,done+1);btn.disabled=true;stats()};
function renderQuiz(){const e=document.querySelector('#quiz');e.innerHTML=`<div class="head"><div><h2>Visual Quiz</h2><p>Choose the best preposition.</p></div><span class="badge">9 questions</span></div><div class="grid">${quiz.map((q,i)=>`<article class="card"><div class="visual"><div class="cube"></div><span class="sym">${q[0]}</span></div><strong>${i+1}. ${q[1]}</strong><div class="opts" data-i="${i}">${q[3].map(o=>`<button class="opt" data-v="${o}">${o}</button>`).join('')}</div><div id="fb${i}" class="feedback"></div></article>`).join('')}</div><div class="actions"><button id="finishQuiz" class="primary">Finish activity</button></div>`;e.querySelectorAll('.opt').forEach(b=>b.addEventListener('click',()=>{const box=b.parentElement;if(box.dataset.done)return;const i=+box.dataset.i,ok=b.dataset.v===quiz[i][2];box.dataset.done='1';box.querySelectorAll('.opt').forEach(x=>{if(x.dataset.v===quiz[i][2])x.classList.add('correct')});if(!ok)b.classList.add('wrong');document.querySelector('#fb'+i).textContent=ok?'✓ Correct!':'Correct answer: '+quiz[i][2]}));document.querySelector('#finishQuiz').addEventListener('click',e=>{const d=document.querySelectorAll('#quiz [data-done="1"]').length;if(d<9)return alert('Answer all 9 questions first.');const good=document.querySelectorAll('#quiz .opt.correct').length-document.querySelectorAll('#quiz .opt.wrong').length;finish(Math.max(0,good)*10,e.currentTarget)})}
function renderFill(){const e=document.querySelector('#fill');e.innerHTML=`<div class="head"><div><h2>Complete the Sentences</h2><p>Select the correct preposition.</p></div><span class="badge">6 questions</span></div><div class="sentences">${fill.map((x,i)=>`<label class="sentence">${i+1}. ${x[0]}<select data-i="${i}"><option value="">Choose...</option>${P.map(p=>`<option>${p}</option>`).join('')}</select></label>`).join('')}</div><div class="actions"><button id="checkFill" class="primary">Check answers</button></div><div id="fillResult" class="result hidden"></div>`;document.querySelector('#checkFill').addEventListener('click',ev=>{const s=[...e.querySelectorAll('select')];if(s.some(x=>!x.value))return alert('Complete every sentence first.');let n=0;s.forEach((x,i)=>{if(x.value===fill[i][1]){n++;x.style.borderColor='#45d4a8'}else x.style.borderColor='#fb7185'});const r=document.querySelector('#fillResult');r.classList.remove('hidden');r.textContent=`You got ${n}/6 correct.`;finish(n*10,ev.currentTarget)})}
function renderMatch(){const e=document.querySelector('#match');const defs=pairs.map((p,i)=>[i,p[1]]).sort(()=>Math.random()-.5);e.innerHTML=`<div class="head"><div><h2>Match the Meaning</h2><p>Click a preposition, then its meaning.</p></div><span class="badge">8 pairs</span></div><div class="match"><div class="col">${pairs.map((p,i)=>`<button class="match-btn" data-side="l" data-id="${i}">${p[0]}</button>`).join('')}</div><div class="col">${defs.map(d=>`<button class="match-btn" data-side="r" data-id="${d[0]}">${d[1]}</button>`).join('')}</div></div><div id="matchResult" class="result">0 / 8 matched</div>`;let sel=null,m=0;e.querySelectorAll('.match-btn').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('matched'))return;if(!sel){sel=b;b.classList.add('selected');return}if(sel.dataset.side===b.dataset.side){sel.classList.remove('selected');sel=b;b.classList.add('selected');return}if(sel.dataset.id===b.dataset.id){sel.classList.remove('selected');sel.classList.add('matched');b.classList.add('matched');sel=null;m++;document.querySelector('#matchResult').textContent=`${m} / 8 matched`;if(m===8){score+=80;done++;stats();document.querySelector('#matchResult').textContent='Perfect! 8 / 8 matched ✓'}}else{sel.classList.remove('selected');sel=null}}))}
function renderBuild(){const e=document.querySelector('#build');let i=0,chosen=[];const draw=()=>{if(i>=scrambles.length){e.innerHTML=`<div class="head"><div><h2>Sentence Builder</h2><p>Challenge complete.</p></div></div><div class="result">Excellent! You built all 3 sentences correctly. ✓</div>`;score+=60;done++;stats();return}const [ans,words]=scrambles[i];e.innerHTML=`<div class="head"><div><h2>Sentence Builder</h2><p>Click the words in the correct order.</p></div><span class="badge">${i+1}/3</span></div><div class="builder"><div id="answer" class="answer">Your sentence will appear here...</div><div class="tokens">${words.map((w,j)=>`<button class="token" data-j="${j}">${w}</button>`).join('')}</div><div class="actions"><button id="checkBuild" class="primary">Check</button><button id="clearBuild" class="secondary">Clear</button></div><div id="buildFb" class="feedback"></div></div>`;e.querySelectorAll('.token').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('used'))return;chosen.push(words[+b.dataset.j]);b.classList.add('used');document.querySelector('#answer').innerHTML=chosen.map(w=>`<span class="token">${w}</span>`).join('')}));document.querySelector('#clearBuild').addEventListener('click',()=>{chosen=[];draw()});document.querySelector('#checkBuild').addEventListener('click',()=>{if(chosen.join(' ')===ans){document.querySelector('#buildFb').textContent='✓ Correct!';setTimeout(()=>{i++;chosen=[];draw()},500)}else document.querySelector('#buildFb').textContent='Try again.'})};draw()}
renderQuiz();renderFill();renderMatch();renderBuild();document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.act').forEach(x=>x.classList.add('hidden'));document.querySelector('#'+t.dataset.tab).classList.remove('hidden')}));
